/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulator;
import javax.swing.JOptionPane;
/**
 * 
 * @author wiktoria
 */
public class KalkulatorFrame extends javax.swing.JFrame {
private double minne; //medlemsvariabel som används för att spara minne från M+, M-
private double total1 = 0; // den variabel sparar värde från text field när man trycker på operator till exempel +, -
private double total2 = 0; // den variabel sparar värde som är summa/produkt av operation till exempel 4 är summa av 2+2 så total2 får värde 4
private char math_operator; // den variabel representerar vilket matematik operator man använder till exempel -, +

    /**
     * Creates new form KalkulatorFrame
     */
    public KalkulatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDisplay = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnOne = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnPunkt = new javax.swing.JButton();
        btnPlusMinus = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnMemoryClear = new javax.swing.JButton();
        btnMemoryMinus = new javax.swing.JButton();
        btnMemoryPlus = new javax.swing.JButton();
        btnMemoryRecall = new javax.swing.JButton();
        btnRoten = new javax.swing.JButton();
        btn1delaX = new javax.swing.JButton();
        btnXupp3 = new javax.swing.JButton();
        btnFakultet = new javax.swing.JButton();
        btnXupp2 = new javax.swing.JButton();
        btnXuppY = new javax.swing.JButton();
        lblMemory = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator");

        txtDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnOne.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOne.setText("1");
        btnOne.setMaximumSize(new java.awt.Dimension(50, 30));
        btnOne.setMinimumSize(new java.awt.Dimension(50, 30));
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnTwo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTwo.setText("2");
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnThree.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThree.setText("3");
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnFour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFour.setText("4");
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnFive.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFive.setText("5");
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnSix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSix.setText("6");
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnSeven.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSeven.setText("7");
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEight.setText("8");
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnNine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNine.setText("9");
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnZero.setText("0");
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnPunkt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPunkt.setText(".");
        btnPunkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPunktActionPerformed(evt);
            }
        });

        btnPlusMinus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPlusMinus.setText("+/-");
        btnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPunkt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPunkt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnPlus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnMultiply.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btnDivide.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnEquals.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEquals.setText("=");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnClear.setText("AC");
        btnClear.setMaximumSize(new java.awt.Dimension(75, 29));
        btnClear.setMinimumSize(new java.awt.Dimension(75, 29));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnMemoryClear.setText("MC");
        btnMemoryClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryClearActionPerformed(evt);
            }
        });

        btnMemoryMinus.setText("M-");
        btnMemoryMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryMinusActionPerformed(evt);
            }
        });

        btnMemoryPlus.setText("M+");
        btnMemoryPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryPlusActionPerformed(evt);
            }
        });

        btnMemoryRecall.setText("MR");
        btnMemoryRecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoryRecallActionPerformed(evt);
            }
        });

        btnRoten.setText("sqrt");
        btnRoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotenActionPerformed(evt);
            }
        });

        btn1delaX.setText("1/x");
        btn1delaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1delaXActionPerformed(evt);
            }
        });

        btnXupp3.setText("x^3");
        btnXupp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXupp3ActionPerformed(evt);
            }
        });

        btnFakultet.setText("n!");
        btnFakultet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFakultetActionPerformed(evt);
            }
        });

        btnXupp2.setText("x^2");
        btnXupp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXupp2ActionPerformed(evt);
            }
        });

        btnXuppY.setText("x^y");
        btnXuppY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuppYActionPerformed(evt);
            }
        });

        lblMemory.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMemoryPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFakultet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMemoryMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMemoryRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn1delaX, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRoten, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXupp2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXupp3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXuppY, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMemoryMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMemoryRecall, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMemoryClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMemoryPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFakultet)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRoten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1delaX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXupp2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXupp3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXuppY))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * den metod läser in matematik operator som användare väljer
 * @param btnText 
 */
    
   
    private void getOperator(String btnText){
        math_operator = btnText.charAt(0);
        total1 = total1 + Double.parseDouble(txtDisplay.getText());
        txtDisplay.setText("");
    }
    /**
     * metoden som tömmar displayen 
     * @param evt 
     */
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        total2 = 0;
        txtDisplay.setText("");
    }//GEN-LAST:event_btnClearActionPerformed
/**
 * metod som skriver på displayen den talen som ligger på knappen
 * @param evt 
 */
    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        String btnTwoText = txtDisplay.getText() + btnTwo.getText();
        txtDisplay.setText( btnTwoText );
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        String btnOneText = txtDisplay.getText() + btnOne.getText();
        txtDisplay.setText( btnOneText );
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        String btnThreeText = txtDisplay.getText() + btnThree.getText();
        txtDisplay.setText( btnThreeText );
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        String btnFourText = txtDisplay.getText() + btnFour.getText();
txtDisplay.setText( btnFourText );
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        String btnFiveText = txtDisplay.getText() + btnFive.getText();
txtDisplay.setText( btnFiveText );
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        String btnSixText = txtDisplay.getText() + btnSix.getText();
txtDisplay.setText( btnSixText );
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
      String btnSevenText = txtDisplay.getText() + btnSeven.getText();
txtDisplay.setText( btnSevenText );
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
      String btnEightText = txtDisplay.getText() + btnEight.getText();
txtDisplay.setText( btnEightText );
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        String btnNineText = txtDisplay.getText() + btnNine.getText();
txtDisplay.setText( btnNineText );
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        String btnZeroText = txtDisplay.getText() + btnZero.getText();
txtDisplay.setText( btnZeroText );
    }//GEN-LAST:event_btnZeroActionPerformed

    /**
     * den metod läser operator som ligger på knappen och sen skickar den till getOperator metoden
     * getOperator metod sparar valt operator i math_operator variabel
     * den metod checkar också om det finns något fel och om användaren gör något fel så ska lämplig meddelande visas
     * @param evt 
     */
    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
         if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
            
        }
            String button_text = btnPlus.getText();
            getOperator(button_text);
        
       
        
    }//GEN-LAST:event_btnPlusActionPerformed
/**
 * den metod beräknar olika uttrycker till exempel summa, produkt, kvot
 * först läser det vilket math operator användaren har valt innan och sen beräknar det talen som var lagrat i variabel total1 med talen som finns nu på displayen
 * det också hanterar olika fel som kan ske
 * @param evt 
 */
    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
         
        switch ( math_operator ) {
        case '+':
             
           
            total2 = total1 + Double.parseDouble(txtDisplay.getText());
            
          
            if (total2 - Math.floor(total2) == 0 ){ //The Math.floor() function returns the largest integer less than or equal to a given number.
             int produkt = (int)total2; // omvandla produkt till int
            txtDisplay.setText(Integer.toString(produkt)); // skriver ut produkten med int i text field
         }
         else {
             txtDisplay.setText(Double.toString(total2)); // skriver ut produkten med double till text field
         }
            
            break;
            
        case '-':
            
            total2 = total1 - Double.parseDouble(txtDisplay.getText());
           
            if(total2 - Math.floor(total2) == 0) {
                int produkt = (int)total2;
                txtDisplay.setText(Integer.toString(produkt));
            }
            else {
             txtDisplay.setText(Double.toString(total2));   
            }
            break;
        case '/':
          
            total2 = total1 / Double.parseDouble(txtDisplay.getText());
            
             if(total2 - Math.floor(total2) == 0) {
                int produkt = (int)total2;
                txtDisplay.setText(Integer.toString(produkt));
            }
            else {
             txtDisplay.setText(Double.toString(total2));   
            }
            break;
        case '*':
           
            total2 = total1 * Double.parseDouble(txtDisplay.getText());
            
             if(total2 - Math.floor(total2) == 0) {
                int produkt = (int)total2;
                txtDisplay.setText(Integer.toString(produkt));
            }
            else {
             txtDisplay.setText(Double.toString(total2));   
            }
            break;

        
        case 'x': // jag har använd den här case för att beräkna x^y, jag gjorde det för att jag behövde lagra första tal för x och
                    //och sen måste jag beräkna det med nästa talen som användaren ska skriva
                    // jag har använd Math.power för att beräkna den här uttryck
         
            total2 = Math.pow(total1, Double.parseDouble(txtDisplay.getText()));
            
             if(total2 - Math.floor(total2) == 0) {
                int produkt = (int)total2;
                txtDisplay.setText(Integer.toString(produkt));
            }
            else {
             txtDisplay.setText(Double.toString(total2));   
            }
            break;
        
        }
       
        total1 = 0; // efter varje beräkning total1 är 0 igen för att man kunna räkna vidare andra uttrycker
        if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
            
        }
    }//GEN-LAST:event_btnEqualsActionPerformed
/**
 * den metod bara skriver punkt om man använder decimaltal
 * @param evt 
 */
    private void btnPunktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPunktActionPerformed
       if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
            
        }
        String btnPunktText = txtDisplay.getText();
        if(btnPunktText.contains(".")){
          txtDisplay.setText(btnPunktText);  
        }
        else{
       txtDisplay.setText( btnPunktText + "." );
        }
    }//GEN-LAST:event_btnPunktActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
      if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
            
        }
        String button_text = btnMinus.getText();
        getOperator(button_text);
      
         
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
            
        }
        String button_text = btnMultiply.getText();
        getOperator(button_text);
       
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
     if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
            
        }
        String button_text = btnDivide.getText();
        getOperator(button_text);
       
    }//GEN-LAST:event_btnDivideActionPerformed
/**
 * när man klickar på +/- knapp så talen ska ändra sig till negativ talen eller till positiv talen 
 * @param evt 
 */
    private void btnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinusActionPerformed
           if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
            
        }  
        double tal = Double.parseDouble(txtDisplay.getText()); // först tilldelar värde från displayen till double variabel
            
            if (tal > 0){ // om talen i displayen är större än noll så ska det ändra sig till negativ talen
            String omvandlaTillminus = "-" + txtDisplay.getText();
            txtDisplay.setText(omvandlaTillminus);
            
            }
            else if(tal == 0){
                txtDisplay.setText("0");
            }
            else {
               // om talen på displayen är mindre än 0 så ska det ändra sig till positiv talen
               //genom substring metoden som läser string fråm andra position dvs utan - tecken
            String omvandlaTillplus = txtDisplay.getText();
            String plus = omvandlaTillplus.substring(1);
            txtDisplay.setText(plus); 
            
            }
            
    }//GEN-LAST:event_btnPlusMinusActionPerformed
/**
 * den metod beräknar fraktion dvs 1 är delat med talen på displayen
 * @param evt 
 */
    private void btn1delaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1delaXActionPerformed
        if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
            
        }
        
        double frakt = Double.parseDouble(txtDisplay.getText());
        if (frakt == 0){
            txtDisplay.setText("Error");
            return;
        }
        double fraktion = 1 / Double.parseDouble(txtDisplay.getText());
        if(fraktion - Math.floor(fraktion) == 0) {
                int produkt = (int)fraktion;
                txtDisplay.setText(Integer.toString(produkt));
            }
            else {
             txtDisplay.setText(Double.toString(fraktion));   
            }
    }//GEN-LAST:event_btn1delaXActionPerformed
/**
 * den metod beräknar roten med Math.sqrt klassen och också visar integer om talen är inte decimaltal
 * @param evt 
 */
    private void btnRotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotenActionPerformed
        
        if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
        }
        
        double roten = Double.parseDouble(txtDisplay.getText());
        if (roten < 0){
            txtDisplay.setText("Error");
            return;
        }
        double rot = Math.sqrt(Double.parseDouble(txtDisplay.getText()));
        
        
         if(rot - Math.floor(rot) == 0) {
                int produkt = (int)rot;
                txtDisplay.setText(Integer.toString(produkt));
            }
            else {
             txtDisplay.setText(Double.toString(rot));   
            }
        
       
        
    }//GEN-LAST:event_btnRotenActionPerformed
/**
 * metoden beräknar kvadrat av talen x som användaren väljer själv 
 * till exempel när man klickar på 4 och sen på knappen x^2 så ska 16 visas på displayen, 4 * 4 = 16
 * @param evt 
 */
    private void btnXupp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXupp2ActionPerformed
        if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
        }
        double kvadratera = Math.pow(Double.parseDouble(txtDisplay.getText()), 2);
        if(kvadratera - Math.floor(kvadratera) == 0) {
                int produkt = (int)kvadratera;
                txtDisplay.setText(Integer.toString(produkt));
            }
            else {
             txtDisplay.setText(Double.toString(kvadratera));   
            }
        
    }//GEN-LAST:event_btnXupp2ActionPerformed

    private void btnXupp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXupp3ActionPerformed
         if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
        }
        double upp3 = Math.pow(Double.parseDouble(txtDisplay.getText()), 3);
        if(upp3 - Math.floor(upp3) == 0) {
                int produkt = (int)upp3;
                txtDisplay.setText(Integer.toString(produkt));
            }
            else {
             txtDisplay.setText(Double.toString(upp3));   
            }
    }//GEN-LAST:event_btnXupp3ActionPerformed
/**
 * metod som beräknar x^y, först måste man klicka på knappen med talen, sedan på knappen x^y, sedan på knappen =
 * @param evt 
 */
    private void btnXuppYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuppYActionPerformed
      if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
        }
            String button_text = btnXuppY.getText();
            getOperator(button_text);
        
        
        
        
        
    }//GEN-LAST:event_btnXuppYActionPerformed
/**
 * den metoden beräknar fakultet dvs n!, det är lite komplicerat beräkning och har jag använd extra metod som heter multiplicera
 * multiplicera metod beräknar fakultet
 * jag har använd long som typ av värde för att man kunna beräkna största talen
 * i den här metoden vill jag hantera två olika fel exception som kan ske
 * @param evt 
 */
    private void btnFakultetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFakultetActionPerformed
        if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
        }
          try{
         long tal = Long.parseLong(txtDisplay.getText());
         if (tal < 0){
           txtDisplay.setText("Error"); 
           return;
         }
          
         long fakultet = 1;
        for (long i = 1; i <= tal; i++){
            fakultet = fakultet * i;
        }
          txtDisplay.setText(Long.toString(fakultet));
          }
          
          catch (NumberFormatException e){
            txtDisplay.setText("Error");  
          }
        
      
    }//GEN-LAST:event_btnFakultetActionPerformed
/**
 * den metod tömmar minne
 * @param evt 
 */
    private void btnMemoryClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryClearActionPerformed
        minne = 0.0;
        lblMemory.setText("");
    }//GEN-LAST:event_btnMemoryClearActionPerformed
/**
 * den metod lägger talen på displayen i minne men först gör att det ska vara en negativ tal
 * @param evt 
 */
    private void btnMemoryMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryMinusActionPerformed
        if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
        }
        double minusMinne = Double.parseDouble(txtDisplay.getText());
        minne -= minusMinne; 

              
        
       lblMemory.setText("    M"); // det gör att M ska synas på kalkulator som visas att det finns minne 
        
    }//GEN-LAST:event_btnMemoryMinusActionPerformed

    private void btnMemoryPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryPlusActionPerformed
       if(txtDisplay.getText().equals("")){
            txtDisplay.setText("0");
        }
        double plusMinne = Double.parseDouble(txtDisplay.getText());
        minne += plusMinne;
        
       lblMemory.setText("    M"); 
    }//GEN-LAST:event_btnMemoryPlusActionPerformed
/**
 * metod som visas minne på displayen , om minne är lika med 0 så ska bara 0 synas
 * @param evt 
 */
    private void btnMemoryRecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoryRecallActionPerformed
        if (minne == 0){
          txtDisplay.setText("0");  
        }
        else { 
            
            
            if(minne - Math.floor(minne) == 0) {
                int produkt = (int)minne;
                txtDisplay.setText(Integer.toString(produkt));
            }
            else {
             txtDisplay.setText(Double.toString(minne));   
            }
           
       
       
        }
         
    }//GEN-LAST:event_btnMemoryRecallActionPerformed
    /**
     * metod som beräknar fakultet n!, det är advänds bara i private void btnFakultetActionPerformed(java.awt.event.ActionEvent evt)         
     * @param n
     * @return 
     */
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1delaX;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnFakultet;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMemoryClear;
    private javax.swing.JButton btnMemoryMinus;
    private javax.swing.JButton btnMemoryPlus;
    private javax.swing.JButton btnMemoryRecall;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnPunkt;
    private javax.swing.JButton btnRoten;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnXupp2;
    private javax.swing.JButton btnXupp3;
    private javax.swing.JButton btnXuppY;
    private javax.swing.JButton btnZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMemory;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
